<?php
/**
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see https://www.gnu.org/licenses/.
 */

$this->smarty->assign('REGISTRATION_ORDER', __('REGISTRATION ORDER', 'correosoficial'));
$this->smarty->assign('Required_field', __('Required field', 'correosoficial'));
$this->smarty->assign('Please_specify_a_valid_Bank_Account_number_IBAN', __('Please specify a valid Bank Account number_IBAN', 'correosoficial'));
$this->smarty->assign('Please_enter_a_valid_email_address', __('Please enter a valid email address', 'correosoficial'));
$this->smarty->assign('Please_enter_a_valid_number', __('Please enter a valid number', 'correosoficial'));
$this->smarty->assign('Incorrect_DNI_CIF_number__please_correct_it_before_continuing', __('Incorrect DNI_CIF number, please correct it before continuing', 'correosoficial'));
$this->smarty->assign('Please_enter_at_least', __('Please enter at least', 'correosoficial'));
$this->smarty->assign('Please_enter_no_more_than', __('Please enter no more than', 'correosoficial'));
$this->smarty->assign('characters', __('characters', 'correosoficial'));
$this->smarty->assign('Sender_Data', __('Sender Data', 'correosoficial'));
$this->smarty->assign('Default_sender', __('Default sender', 'correosoficial'));
$this->smarty->assign('You_have_not_configured_any_default_sender', __('You have not configured any default sender', 'correosoficial'));
$this->smarty->assign('Name', __('Name', 'correosoficial'));
$this->smarty->assign('Contact_person', __('Contact person', 'correosoficial'));
$this->smarty->assign('Address', __('Address', 'correosoficial'));
$this->smarty->assign('City', __('City', 'correosoficial'));
$this->smarty->assign('Postal_code', __('Postal code', 'correosoficial'));
$this->smarty->assign('Country', __('Country', 'correosoficial'));
$this->smarty->assign('Select_a_country', __('Select a country', 'correosoficial'));
$this->smarty->assign('Spain', __('Spain', 'correosoficial'));
$this->smarty->assign('Portugal', __('Portugal', 'correosoficial'));
$this->smarty->assign('Andorra', __('Andorra', 'correosoficial'));
$this->smarty->assign('Phone_number', __('Phone number', 'correosoficial'));
$this->smarty->assign('Email', __('Email', 'correosoficial'));
$this->smarty->assign('NIF_CIF', __('NIF_CIF', 'correosoficial'));
$this->smarty->assign('Recipient_Data', __('Recipient Data', 'correosoficial'));
$this->smarty->assign('Surnames', __('Surnames', 'correosoficial'));
$this->smarty->assign('Company', __('Company', 'correosoficial'));
$this->smarty->assign('SELECTED_OFFICE', __('SELECTED OFFICE', 'correosoficial'));
$this->smarty->assign('Change_office', __('Change office', 'correosoficial'));
$this->smarty->assign('Search', __('Search', 'correosoficial'));
$this->smarty->assign('Offices_found', __('Offices found', 'correosoficial'));
$this->smarty->assign('Choose_office', __('Choose office', 'correosoficial'));
$this->smarty->assign('Office_information', __('Office information', 'correosoficial'));
$this->smarty->assign('CityPAQ_SELECTED', __('CityPAQ SELECTED', 'correosoficial'));
$this->smarty->assign('Change_CityPAQ', __('Change CityPAQ', 'correosoficial'));
$this->smarty->assign('CityPAQ_found', __('CityPAQ found', 'correosoficial'));
$this->smarty->assign('Choose_CityPAQ', __('Choose CityPAQ', 'correosoficial'));
$this->smarty->assign('CityPAQ_information', __('CityPAQ information', 'correosoficial'));
$this->smarty->assign('ORDER_DATA', __('ORDER DATA', 'correosoficial'));
$this->smarty->assign('Phone', __('Phone', 'correosoficial'));
$this->smarty->assign('Shipping_data', __('Shipping data', 'correosoficial'));
$this->smarty->assign('Billing_customer_code', __('Billing customer code', 'correosoficial'));
$this->smarty->assign('Carriers', __('Carriers', 'correosoficial'));
$this->smarty->assign('You_have_not_configured_any_carrier', __('You have not configured any carrier', 'correosoficial'));
$this->smarty->assign('Carrier', __('Carrier', 'correosoficial'));
$this->smarty->assign('Shipper_s_customs_reference', __('Shipper\s customs reference', 'correosoficial'));
$this->smarty->assign('Shipping_reference', __('Shipping reference', 'correosoficial'));
$this->smarty->assign('Description_reference____', __('Description reference (1)', 'correosoficial'));
$this->smarty->assign('Description_reference____', __('Description reference (2)', 'correosoficial'));
$this->smarty->assign('AT_code', __('AT code', 'correosoficial'));
$this->smarty->assign('Package_error__The_selected_carrier_only_allows_a_single_package', __('Package error: The selected carrier only allows a single package', 'correosoficial'));
$this->smarty->assign('Packages', __('Packages', 'correosoficial'));
$this->smarty->assign('Number_of_packages', __('Number of packages', 'correosoficial'));
$this->smarty->assign('All_similar_packages', __('All similar packages', 'correosoficial'));
$this->smarty->assign('Package', __('Package', 'correosoficial'));
$this->smarty->assign('Reference', __('Reference', 'correosoficial'));
$this->smarty->assign('Weight', __('Weight', 'correosoficial'));
$this->smarty->assign('Long', __('Long', 'correosoficial'));
$this->smarty->assign('Width', __('Width', 'correosoficial'));
$this->smarty->assign('High', __('High', 'correosoficial'));
$this->smarty->assign('Delivery_remarks', __('Delivery remarks', 'correosoficial'));
$this->smarty->assign('Customs_related_data', __('Customs related data', 'correosoficial'));
$this->smarty->assign('Net_value', __('Net value', 'correosoficial'));
$this->smarty->assign('Customs_default_description', __('Customs default description', 'correosoficial'));
$this->smarty->assign('Tariff', __('Tariff', 'correosoficial'));
$this->smarty->assign('Description', __('Description', 'correosoficial'));
$this->smarty->assign('Added_value_of_the_shipment', __('Added value of the shipment', 'correosoficial'));
$this->smarty->assign('Cash_on_delivery', __('Cash on delivery', 'correosoficial'));
$this->smarty->assign('Cash_on_delivery_value', __('Cash on delivery value', 'correosoficial'));
$this->smarty->assign('Bank_account_number___IBAN', __('Bank account number _ IBAN', 'correosoficial'));
$this->smarty->assign('Insurance', __('Insurance', 'correosoficial'));
$this->smarty->assign('Insured_value', __('Insured value', 'correosoficial'));
$this->smarty->assign('Partial_delivery', __('Partial delivery', 'correosoficial'));
$this->smarty->assign('Saturday_pick_up', __('Saturday pick up', 'correosoficial'));
$this->smarty->assign('Register_shipment', __('Register shipment', 'correosoficial'));
$this->smarty->assign('Processing', __('Processing', 'correosoficial'));
$this->smarty->assign('Cancel_shipping', __('Cancel shipping', 'correosoficial'));
$this->smarty->assign('Generate_shipping', __('Generate shipping', 'correosoficial'));
$this->smarty->assign('Generate_pickup', __('Generate pickup', 'correosoficial'));
$this->smarty->assign('Pickup_date', __('Pickup date', 'correosoficial'));
$this->smarty->assign('From', __('From', 'correosoficial'));
$this->smarty->assign('To', __('To', 'correosoficial'));
$this->smarty->assign('Print_Post_Label', __('Print Post Label', 'correosoficial'));
$this->smarty->assign('Only_Correos_shipments__Click_if_Correos_must_have_the_labels_printed_on_the_collection', __('Only Correos shipments. Click if Correos must have the labels printed on the collection', 'correosoficial'));
$this->smarty->assign('Not_available_for_shipments_with_more_than___packages', __('Not available for shipments with more than 5 packages', 'correosoficial'));
$this->smarty->assign('Package_size', __('Package size', 'correosoficial'));
$this->smarty->assign('Envelopes', __('Envelopes', 'correosoficial'));
$this->smarty->assign('Small__shoebox_', __('Small (shoebox)', 'correosoficial'));
$this->smarty->assign('Medium__Folio_box_', __('Medium (Folio box)', 'correosoficial'));
$this->smarty->assign('Large__box___x__x__cm_', __('Large (box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Very_large__larger_than_box___x__x__cm_', __('Very large (larger than box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Pallet', __('Pallet', 'correosoficial'));
$this->smarty->assign('Only_Correos_shipments__Select_package_size_for_pickup_', __('Only Correos shipments. Select package size for pickup.', 'correosoficial'));
$this->smarty->assign('Collection_data', __('Collection data', 'correosoficial'));
$this->smarty->assign('Pick_up_code', __('Pick-up code', 'correosoficial'));
$this->smarty->assign('reference', __('reference', 'correosoficial'));
$this->smarty->assign('Pickup_data', __('Pickup data', 'correosoficial'));
$this->smarty->assign('Cancel_pickup', __('Cancel pickup', 'correosoficial'));
$this->smarty->assign('status', __('status', 'correosoficial'));
$this->smarty->assign('Registered_shipping_data', __('Registered shipping data', 'correosoficial'));
$this->smarty->assign('Shipping_code', __('Shipping code', 'correosoficial'));
$this->smarty->assign('Shipping_codes', __('Shipping codes', 'correosoficial'));
$this->smarty->assign('Print_CN__', __('Print CN23', 'correosoficial'));
$this->smarty->assign('Print_DUA', __('Print DUA', 'correosoficial'));
$this->smarty->assign('Print_DDP', __('Print DDP', 'correosoficial'));
$this->smarty->assign('Label_type', __('Label type', 'correosoficial'));
$this->smarty->assign('Label_position', __('Label position', 'correosoficial'));
$this->smarty->assign('Print_label', __('Print label', 'correosoficial'));
$this->smarty->assign('Error_operation', __('Error operation', 'correosoficial'));
$this->smarty->assign('Done_operation', __('Done operation', 'correosoficial'));
$this->smarty->assign('Shipping_status', __('Shipping status', 'correosoficial'));
$this->smarty->assign('Status', __('Status', 'correosoficial'));
$this->smarty->assign('Date', __('Date', 'correosoficial'));
$this->smarty->assign('Shipper_s_customs_reference', __('Shipper s customs reference', 'correosoficial'));
$this->smarty->assign('Customs_reference_of_consignor', __('Customs reference of consignor', 'correosoficial'));
$this->smarty->assign('Office_error', __('Office error', 'correosoficial'));
$this->smarty->assign('No_offices_found', __('No offices found', 'correosoficial'));
$this->smarty->assign('Citypaq_error', __('Citypaq error', 'correosoficial'));
$this->smarty->assign('No_citypaqs_found', __('No citypaqs found', 'correosoficial'));
$this->smarty->assign('Print_Label', __('Print Label', 'correosoficial'));
$this->smarty->assign('Returns', __('Returns', 'correosoficial'));
$this->smarty->assign('Number_of_packages_return', __('Number of packages return', 'correosoficial'));
$this->smarty->assign('Generate_return', __('Generate return', 'correosoficial'));
$this->smarty->assign('Cancel_return', __('Cancel return', 'correosoficial'));
$this->smarty->assign('Return_data', __('Return data', 'correosoficial'));
$this->smarty->assign('Return_codes', __('Return codes', 'correosoficial'));
$this->smarty->assign('Error_while_registering', __('Error while registering', 'correosoficial'));
$this->smarty->assign('Package_return', __('Package return', 'correosoficial'));
$this->smarty->assign('Generate_return_pickup', __('Generate return pickup', 'correosoficial'));
$this->smarty->assign('Return_pickup_data', __('Return pickup data', 'correosoficial'));
$this->smarty->assign('Return_pickup_code', __('Return pickup code', 'correosoficial'));
$this->smarty->assign('Pickup_code', __('Pickup code', 'correosoficial'));
$this->smarty->assign('Hour', __('Hour', 'correosoficial'));
$this->smarty->assign('Sender', __('Sender', 'correosoficial'));
$this->smarty->assign('Select_a_product', __('Select a product', 'correosoficial'));
$this->smarty->assign('Edit_Sender', __('Edit Sender', 'correosoficial'));
$this->smarty->assign('The_locator_service_is_temporarily_unavailable__Please__try_again_later', __('The locator service is temporarily unavailable. Please, try again later', 'correosoficial'));
$this->smarty->assign('Print_DCAF', __('Print DCAF', 'correosoficial'));
$this->smarty->assign('Volumetric_weight', __('Volumetric weight', 'correosoficial'));
$this->smarty->assign('Shipping', __('Shipping', 'correosoficial'));
$this->smarty->assign('Units', __('Units', 'correosoficial'));
$this->smarty->assign('Max____Descriptions', __('Max. 5 Descriptions', 'correosoficial'));
$this->smarty->assign('Add_and_save', __('Add and save', 'correosoficial'));
$this->smarty->assign('Delete', __('Delete', 'correosoficial'));
$this->smarty->assign('Send_Documentation_by_email', __('Send Documentation by email', 'correosoficial'));
$this->smarty->assign('Height', __('Height', 'correosoficial'));
$this->smarty->assign('Request_labelling_from_Correos', __('Request labelling from Correos', 'correosoficial'));
$this->smarty->assign('Tariff_Code', __('Tariff Code', 'correosoficial'));
$this->smarty->assign('Product_Return', __('Product Return', 'correosoficial'));
$this->smarty->assign('Input_a_valid_number_without_symbols_or_blank_spaces', __('Input a valid number without symbols or blank spaces', 'correosoficial'));
$this->smarty->assign('Label_Format', __('Label Format', 'correosoficial'));
$this->smarty->assign('Save_pickup', __('Save pickup', 'correosoficial'));
$this->smarty->assign('From_hour', __('From hour', 'correosoficial'));
$this->smarty->assign('To_hour', __('To hour', 'correosoficial'));
$this->smarty->assign('Print_label_at_pickup', __('Print label at pickup', 'correosoficial'));
$this->smarty->assign('Package_Size', __('Package Size', 'correosoficial'));
$this->smarty->assign('Small__Shoes_Box_', __('Small (Shoes Box)', 'correosoficial'));
$this->smarty->assign('Medium__Sheet_Box_', __('Medium (Sheet Box)', 'correosoficial'));
$this->smarty->assign('Big__box___x__x__cm_', __('Big (box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Very_Big__greather_than_box___x__x__cm_', __('Very Big (greather than box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Pallete', __('Pallete', 'correosoficial'));
$this->smarty->assign('Messages_center', __('Messages center', 'correosoficial'));
$this->smarty->assign('Click_on_any_notification_to_see_it_in_this_space_in_more_detail', __('Click on any notification to see it in this space in more detail', 'correosoficial'));
$this->smarty->assign('You_don_t_have_any_notification', __("You don\t have any notification", 'correosoficial'));
$this->smarty->assign('To_use_our_module_you_must_accept_our_conditions_', __('To use our module you must accept our conditions.', 'correosoficial'));
$this->smarty->assign('I_have_read_and_accept_the_', __('I have read and accept the ', 'correosoficial'));
$this->smarty->assign('terms_and_conditions', __('terms and conditions', 'correosoficial'));
$this->smarty->assign('data_protection_policy_', __('data protection policy.', 'correosoficial'));
$this->smarty->assign('I_ACCEPT', __('I ACCEPT', 'correosoficial'));
$this->smarty->assign('does_not_have_a_contract_assigned_for', __('does not have a contract assigned for', 'correosoficial'));
$this->smarty->assign('__you_must_change_the_sender__or_configure_a_sender_with_a_valid_contract', __(', you must change the sender, or configure a sender with a valid contract', 'correosoficial'));
$this->smarty->assign('You_currently_do_not_have_any_sender_configured', __('You currently do not have any sender configured', 'correosoficial'));
$this->smarty->assign('Change_Sender', __('Change Sender', 'correosoficial'));
$this->smarty->assign('Set_a_Sender', __('Set a Sender', 'correosoficial'));
$this->smarty->assign('The_minimum_dimensions_of_a_shipment_are____x____x___cm_', __('The minimum dimensions of a shipment are 15 x 10 x 1 cm.', 'correosoficial'));
$this->smarty->assign('TRACKING_ORDER', __('TRACKING ORDER', 'correosoficial'));
$this->smarty->assign('Order_tracking', __('Order tracking', 'correosoficial'));

$this->smarty->assign('does_not_have_a_contract_assigned_for', __('does not have a contract assigned for', 'correosoficial'));
$this->smarty->assign('__you_must_change_the_sender__or_configure_a_sender_with_a_valid_contract', __(', you must change the sender, or configure a sender with a valid contract', 'correosoficial'));
$this->smarty->assign('You_currently_do_not_have_any_sender_configured', __('You currently do not have any sender configured', 'correosoficial'));
$this->smarty->assign('Change_Sender', __('Change Sender', 'correosoficial'));
$this->smarty->assign('Set_a_Sender', __('Set a Sender', 'correosoficial'));
$this->smarty->assign('REGISTRATION_ORDER', __('REGISTRATION ORDER', 'correosoficial'));
$this->smarty->assign('Required_field', __('Required field', 'correosoficial'));
$this->smarty->assign('Please_specify_a_valid_Bank_Account_number_IBAN', __('Please specify a valid Bank Account number_IBAN', 'correosoficial'));
$this->smarty->assign('Please_enter_a_valid_email_address', __('Please enter a valid email address', 'correosoficial'));
$this->smarty->assign('Input_a_valid_number_without_symbols_or_blank_spaces', __('Input a valid number without symbols or blank spaces', 'correosoficial'));
$this->smarty->assign('Incorrect_DNI_CIF_number__please_correct_it_before_continuing', __('Incorrect DNI_CIF number, please correct it before continuing', 'correosoficial'));
$this->smarty->assign('Please_enter_at_least', __('Please enter at least', 'correosoficial'));
$this->smarty->assign('Please_enter_no_more_than', __('Please enter no more than', 'correosoficial'));
$this->smarty->assign('characters', __('characters', 'correosoficial'));
$this->smarty->assign('The_minimum_dimensions_of_a_shipment_are____x____x___cm_', __('The minimum dimensions of a shipment are 15 x 10 x 1 cm.', 'correosoficial'));
$this->smarty->assign('Register_shipment', __('Register shipment', 'correosoficial'));
$this->smarty->assign('Processing', __('Processing', 'correosoficial'));
$this->smarty->assign('Cancel_shipping', __('Cancel shipping', 'correosoficial'));
$this->smarty->assign('Save_pickup', __('Save pickup', 'correosoficial'));
$this->smarty->assign('Pickup_date', __('Pickup date', 'correosoficial'));
$this->smarty->assign('From_hour', __('From hour', 'correosoficial'));
$this->smarty->assign('To_hour', __('To hour', 'correosoficial'));
$this->smarty->assign('Print_label_at_pickup', __('Print label at pickup', 'correosoficial'));
$this->smarty->assign('Package_Size', __('Package Size', 'correosoficial'));
$this->smarty->assign('Envelopes', __('Envelopes', 'correosoficial'));
$this->smarty->assign('Small__Shoes_Box_', __('Small (Shoes Box)', 'correosoficial'));
$this->smarty->assign('Medium__Sheet_Box_', __('Medium (Sheet Box)', 'correosoficial'));
$this->smarty->assign('Big__box___x__x__cm_', __('Big (box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Very_Big__greather_than_box___x__x__cm_', __('Very Big (greather than box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Pallete', __('Pallete', 'correosoficial'));
$this->smarty->assign('Generate_shipping', __('Generate shipping', 'correosoficial'));
$this->smarty->assign('Generate_pickup', __('Generate pickup', 'correosoficial'));
$this->smarty->assign('From', __('From', 'correosoficial'));
$this->smarty->assign('To', __('To', 'correosoficial'));
$this->smarty->assign('Request_labelling_from_Correos', __('Request labelling from Correos', 'correosoficial'));
$this->smarty->assign('Print_Label', __('Print Label', 'correosoficial'));
$this->smarty->assign('Not_available_for_shipments_with_more_than___packages', __('Not available for shipments with more than 5 packages', 'correosoficial'));
$this->smarty->assign('Package_size', __('Package size', 'correosoficial'));
$this->smarty->assign('Small__shoebox_', __('Small (shoebox)', 'correosoficial'));
$this->smarty->assign('Medium__Folio_box_', __('Medium (Folio box)', 'correosoficial'));
$this->smarty->assign('Large__box___x__x__cm_', __('Large (box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Very_large__larger_than_box___x__x__cm_', __('Very large (larger than box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Pallet', __('Pallet', 'correosoficial'));
$this->smarty->assign('Pickup_data', __('Pickup data', 'correosoficial'));
$this->smarty->assign('Pickup_code', __('Pickup code', 'correosoficial'));
$this->smarty->assign('Cancel_pickup', __('Cancel pickup', 'correosoficial'));
$this->smarty->assign('status', __('status', 'correosoficial'));
$this->smarty->assign('Registered_shipping_data', __('Registered shipping data', 'correosoficial'));
$this->smarty->assign('Shipping_code', __('Shipping code', 'correosoficial'));
$this->smarty->assign('Shipping_codes', __('Shipping codes', 'correosoficial'));
$this->smarty->assign('Package', __('Package', 'correosoficial'));
$this->smarty->assign('Label_type', __('Label type', 'correosoficial'));
$this->smarty->assign('Label_Format', __('Label Format', 'correosoficial'));
$this->smarty->assign('Label_position', __('Label position', 'correosoficial'));
$this->smarty->assign('Print_label', __('Print label', 'correosoficial'));
$this->smarty->assign('Print_CN__', __('Print CN23', 'correosoficial'));
$this->smarty->assign('Print_DCAF', __('Print DCAF', 'correosoficial'));
$this->smarty->assign('Print_DDP', __('Print DDP', 'correosoficial'));
$this->smarty->assign('Error_operation', __('Error operation', 'correosoficial'));
$this->smarty->assign('Done_operation', __('Done operation', 'correosoficial'));
$this->smarty->assign('Returns', __('Returns', 'correosoficial'));
$this->smarty->assign('Product_Return', __('Product Return', 'correosoficial'));
$this->smarty->assign('Number_of_packages_return', __('Number of packages return', 'correosoficial'));
$this->smarty->assign('Return_data', __('Return data', 'correosoficial'));
$this->smarty->assign('Return_codes', __('Return codes', 'correosoficial'));
$this->smarty->assign('Status', __('Status', 'correosoficial'));
$this->smarty->assign('Send_Documentation_by_email', __('Send Documentation by email', 'correosoficial'));
$this->smarty->assign('Return_pickup_data', __('Return pickup data', 'correosoficial'));
$this->smarty->assign('Return_pickup_code', __('Return pickup code', 'correosoficial'));
$this->smarty->assign('Package_return', __('Package return', 'correosoficial'));
$this->smarty->assign('Weight', __('Weight', 'correosoficial'));
$this->smarty->assign('Long', __('Long', 'correosoficial'));
$this->smarty->assign('Width', __('Width', 'correosoficial'));
$this->smarty->assign('Height', __('Height', 'correosoficial'));
$this->smarty->assign('Customs_related_data', __('Customs related data', 'correosoficial'));
$this->smarty->assign('Customs_default_description', __('Customs default description', 'correosoficial'));
$this->smarty->assign('Tariff_Code', __('Tariff Code', 'correosoficial'));
$this->smarty->assign('Tariff', __('Tariff', 'correosoficial'));
$this->smarty->assign('Description', __('Description', 'correosoficial'));
$this->smarty->assign('Net_value', __('Net value', 'correosoficial'));
$this->smarty->assign('Units', __('Units', 'correosoficial'));
$this->smarty->assign('Max____Descriptions', __('Max. 5 Descriptions', 'correosoficial'));
$this->smarty->assign('Add_and_save', __('Add and save', 'correosoficial'));
$this->smarty->assign('Delete', __('Delete', 'correosoficial'));
$this->smarty->assign('Generate_return_pickup', __('Generate return pickup', 'correosoficial'));
$this->smarty->assign('Generate_return', __('Generate return', 'correosoficial'));
$this->smarty->assign('Cancel_return', __('Cancel return', 'correosoficial'));
$this->smarty->assign('Error_while_registering', __('Error while registering', 'correosoficial'));
