<?php
/**
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see https://www.gnu.org/licenses/.
 */

$this->smarty->assign('_CUSTOMER_DATA', __(' CUSTOMER DATA', 'correosoficial'));
$this->smarty->assign('_SENDERS', __(' SENDERS', 'correosoficial'));
$this->smarty->assign('_USER_CONFIGURATION', __(' USER CONFIGURATION', 'correosoficial'));
$this->smarty->assign('_CRON', __(' CRON', 'correosoficial'));
$this->smarty->assign('_PRODUCTS', __(' PRODUCTS', 'correosoficial'));
$this->smarty->assign('_ZONES_AND_CARRIERS', __(' ZONES AND CARRIERS', 'correosoficial'));
$this->smarty->assign('_CUSTOMS_PROCESSING', __(' CUSTOMS PROCESSING', 'correosoficial'));
$this->smarty->assign('Only_for_Correos_shippings', __('Only for Correos shippings', 'correosoficial'));
$this->smarty->assign('Connected', __('Connected', 'correosoficial'));
$this->smarty->assign('User', __('User', 'correosoficial'));
$this->smarty->assign('Password', __('Password', 'correosoficial'));
$this->smarty->assign('No_connected', __('No connected', 'correosoficial'));
$this->smarty->assign('Contract_Code', __('Contract Code', 'correosoficial'));
$this->smarty->assign('Customer_Code', __('Customer Code', 'correosoficial'));
$this->smarty->assign('Correos_Key', __('Correos Key', 'correosoficial'));
$this->smarty->assign('OV__User', __('OV2 User', 'correosoficial'));
$this->smarty->assign('Add', __('Add', 'correosoficial'));
$this->smarty->assign('ACTIVE_CUSTOMERS', __('ACTIVE CUSTOMERS', 'correosoficial'));
$this->smarty->assign('id', __('id', 'correosoficial'));
$this->smarty->assign('Company', __('Company', 'correosoficial'));
$this->smarty->assign('Edit', __('Edit', 'correosoficial'));
$this->smarty->assign('Delete', __('Delete', 'correosoficial'));
$this->smarty->assign('Do_you_want_to_delete_this_customer_', __('Do you want to delete this customer?', 'correosoficial'));
$this->smarty->assign('There_is_no_customers_actives_', __('There is no customers actives.', 'correosoficial'));
$this->smarty->assign('Required_field', __('Required field', 'correosoficial'));
$this->smarty->assign('Please_enter_a_valid_email_address', __('Please enter a valid email address', 'correosoficial'));
$this->smarty->assign('Please_enter_at_least', __('Please enter at least', 'correosoficial'));
$this->smarty->assign('Please_enter_no_more_than', __('Please enter no more than', 'correosoficial'));
$this->smarty->assign('characters', __('characters', 'correosoficial'));
$this->smarty->assign('Your_credentials_are_correct_', __('Your credentials are correct.', 'correosoficial'));
$this->smarty->assign('Please__save_your_username_and_password_in_a_safe_way_', __('Please, save your username and password in a safe way.', 'correosoficial'));
$this->smarty->assign('Failed_to_validate_credentials_', __('Failed to validate credentials.', 'correosoficial'));
$this->smarty->assign('The_username_and_password_are_not_correct_', __('The username and password are not correct.', 'correosoficial'));
$this->smarty->assign('Service_Temporaly_unavailable__Please__try_again_later_', __('Service Temporaly unavailable. Please, try again later.', 'correosoficial'));
$this->smarty->assign('Sender_name', __('Sender name', 'correosoficial'));
$this->smarty->assign('Contact_person', __('Contact person', 'correosoficial'));
$this->smarty->assign('Address', __('Address', 'correosoficial'));
$this->smarty->assign('City', __('City', 'correosoficial'));
$this->smarty->assign('Zip_code', __('Zip code', 'correosoficial'));
$this->smarty->assign('Country', __('Country', 'correosoficial'));
$this->smarty->assign('Spain', __('Spain', 'correosoficial'));
$this->smarty->assign('Portugal', __('Portugal', 'correosoficial'));
$this->smarty->assign('Andorra', __('Andorra', 'correosoficial'));
$this->smarty->assign('Phone_number', __('Phone number', 'correosoficial'));
$this->smarty->assign('Email', __('Email', 'correosoficial'));
$this->smarty->assign('NIF_CIF', __('NIF_CIF', 'correosoficial'));
$this->smarty->assign('ADD', __('ADD', 'correosoficial'));
$this->smarty->assign('SAVE', __('SAVE', 'correosoficial'));
$this->smarty->assign('CANCEL', __('CANCEL', 'correosoficial'));
$this->smarty->assign('_SENDER_LIST', __(' SENDER LIST', 'correosoficial'));
$this->smarty->assign('Name', __('Name', 'correosoficial'));
$this->smarty->assign('ZP', __('ZP', 'correosoficial'));
$this->smarty->assign('NIF', __('NIF', 'correosoficial'));
$this->smarty->assign('Contact', __('Contact', 'correosoficial'));
$this->smarty->assign('Phone', __('Phone', 'correosoficial'));
$this->smarty->assign('From', __('From', 'correosoficial'));
$this->smarty->assign('To', __('To', 'correosoficial'));
$this->smarty->assign('Default_sender', __('Default sender', 'correosoficial'));
$this->smarty->assign('Sender_by_default', __('Sender by default', 'correosoficial'));
$this->smarty->assign('Select_a_default_sender', __('Select a default sender', 'correosoficial'));
$this->smarty->assign('SAVE_SENDER_BY_DEFAULT', __('SAVE SENDER BY DEFAULT', 'correosoficial'));
$this->smarty->assign('Sender_successfully_saved', __('Sender successfully saved', 'correosoficial'));
$this->smarty->assign('Incorrect_DNI_CIF_number__please_correct_it_before_continuing', __('Incorrect DNI_CIF number, please correct it before continuing', 'correosoficial'));
$this->smarty->assign('Default_packages', __('Default packages', 'correosoficial'));
$this->smarty->assign('Default_label_type', __('Default label type', 'correosoficial'));
$this->smarty->assign('Method_of_payment_cash_on_delivery', __('Method of payment cash on delivery', 'correosoficial'));
$this->smarty->assign('Select_the_cash_on_delivery_module_active_in_the_store', __('Select the cash on delivery module active in the store', 'correosoficial'));
$this->smarty->assign('Bank_account_number___IBAN', __('Bank account number _ IBAN', 'correosoficial'));
$this->smarty->assign('Only_for_Correos_cash_on_delivery_shippings', __('Only for Correos cash on delivery shippings', 'correosoficial'));
$this->smarty->assign('Google_Maps_API_Key', __('Google Maps API Key', 'correosoficial'));
$this->smarty->assign('Activate_tracking_link_in_the_customer_purchase_history', __('Activate tracking link in the customer purchase history', 'correosoficial'));
$this->smarty->assign('Order_remarks_to_the_label___max_____characters_', __('Order remarks to the label  (max. 80 characters)', 'correosoficial'));
$this->smarty->assign('Alternative_text_for_sender', __('Alternative text for sender', 'correosoficial'));
$this->smarty->assign('Alternative_label_text', __('Alternative label text', 'correosoficial'));
$this->smarty->assign('Activate_default_weight', __('Activate default weight', 'correosoficial'));
$this->smarty->assign('Default_weight__Kg_', __('Default weight (Kg)', 'correosoficial'));
$this->smarty->assign('I_agree_to_alter_product_references_in_shipments', __('I agree to alter product references in shipments', 'correosoficial'));
$this->smarty->assign('Only_Correos_Express_Shippings', __('Only Correos Express Shippings', 'correosoficial'));
$this->smarty->assign('Data_to_display_on_the_label', __('Data to display on the label', 'correosoficial'));
$this->smarty->assign('ID', __('ID', 'correosoficial'));
$this->smarty->assign('NAME', __('NAME', 'correosoficial'));
$this->smarty->assign('SKU', __('SKU', 'correosoficial'));
$this->smarty->assign('EMPTY', __('EMPTY', 'correosoficial'));
$this->smarty->assign('Change_logo_on_labels', __('Change logo on labels', 'correosoficial'));
$this->smarty->assign('Only_CEX_shippings', __('Only CEX shippings', 'correosoficial'));
$this->smarty->assign('SAVE_USER_DATA', __('SAVE USER DATA', 'correosoficial'));
$this->smarty->assign('User_data_successfully_saved', __('User data successfully saved', 'correosoficial'));
$this->smarty->assign('Please_enter_a_value_greater_than_or_equal_to__', __('Please enter a value greater than or equal to 1', 'correosoficial'));
$this->smarty->assign('Please_enter_a_value_less_than_or_equal_to___', __('Please enter a value less than or equal to 10', 'correosoficial'));
$this->smarty->assign('Allowable_value_between___and____kg', __('Allowable value between 1 and 30 kg', 'correosoficial'));
$this->smarty->assign('Please_specify_a_valid_Bank_Account_number_IBAN', __('Please specify a valid Bank Account number_IBAN', 'correosoficial'));
$this->smarty->assign('Select_the_products_to_be_displayed_in_the_checkout', __('Select the products to be displayed in the checkout', 'correosoficial'));
$this->smarty->assign('SAVE_PRODUCTS', __('SAVE PRODUCTS', 'correosoficial'));
$this->smarty->assign('No_Customers_Active', __('No Customers Active', 'correosoficial'));
$this->smarty->assign('You_need_first_to_signup_as_Customer_to_see_your_available_products', __('You need first to signup as Customer to see your available products', 'correosoficial'));
$this->smarty->assign('If_you_already_has_a_Customer_Code__please_go_to_CUSTOMER_DATA', __('If you already has a Customer Code, please go to CUSTOMER DATA', 'correosoficial'));
$this->smarty->assign('Products_successfully_saved', __('Products successfully saved', 'correosoficial'));
$this->smarty->assign('Carriers_with____are_carriers_that_are_not_active', __('Carriers with ** are carriers that are not active', 'correosoficial'));
$this->smarty->assign('It_is_recommended_to_configure_them_for_backward_compatibility', __('It is recommended to configure them for backward compatibility', 'correosoficial'));
$this->smarty->assign('Activate_all_carriers', __('Activate all carriers', 'correosoficial'));
$this->smarty->assign('Select_a_product', __('Select a product', 'correosoficial'));
$this->smarty->assign('SAVE_ZONES_AND_CARRIERS', __('SAVE ZONES AND CARRIERS', 'correosoficial'));
$this->smarty->assign('Zones_and_carriers_successfully_saved', __('Zones and carriers successfully saved', 'correosoficial'));
$this->smarty->assign('Reference_of_customs_consignor', __('Reference of customs consignor', 'correosoficial'));
$this->smarty->assign('Message_to_warn_the_buyer_about_customs_formalities__max______characters_', __('Message to warn the buyer about customs formalities (max. 100 characters)', 'correosoficial'));
$this->smarty->assign('Message_to_warn_the_buyer', __('Message to warn the buyer', 'correosoficial'));
$this->smarty->assign('This_shipment_is_subject_to_customs_clearance__The_price_of_the_shipment_may_be_increased', __('This shipment is subject to customs clearance. The price of the shipment may be increased', 'correosoficial'));
$this->smarty->assign('Select_Customs_Description_or_Default_Tariff_Number', __('Select Customs Description or Default Tariff Number', 'correosoficial'));
$this->smarty->assign('Default_customs_description', __('Default customs description', 'correosoficial'));
$this->smarty->assign('Tariff', __('Tariff', 'correosoficial'));
$this->smarty->assign('Description', __('Description', 'correosoficial'));
$this->smarty->assign('SAVE_CUSTOMS_PROCESSING', __('SAVE CUSTOMS PROCESSING', 'correosoficial'));
$this->smarty->assign('Customs_Processing_successfully_saved', __('Customs Processing successfully saved', 'correosoficial'));
$this->smarty->assign('Confirmation_', __('Confirmation?', 'correosoficial'));
$this->smarty->assign('Cancel', __('Cancel', 'correosoficial'));
$this->smarty->assign('Action', __('Action', 'correosoficial'));
$this->smarty->assign('Accept', __('Accept', 'correosoficial'));
$this->smarty->assign('Information', __('Information', 'correosoficial'));
$this->smarty->assign('An_error_has_occurred', __('An error has occurred', 'correosoficial'));
$this->smarty->assign('Please_specify_a_valid_Bank_Account_number_IBAN', __('Please specify a valid Bank Account number-IBAN', 'correosoficial'));
$this->smarty->assign('Activate_SSL_Certificate', __('Activate SSL Certificate', 'correosoficial'));
$this->smarty->assign('Correos', __('Correos', 'correosoficial'));
$this->smarty->assign('Correos_Express', __('Correos Express', 'correosoficial'));
$this->smarty->assign('Tariff_number', __('Tariff number', 'correosoficial'));
$this->smarty->assign('Tariff_code', __('Tariff code', 'correosoficial'));
$this->smarty->assign('Input_data_must_be______or____characters_long', __('Input data must be 6, 8 or 10 characters long', 'correosoficial'));
$this->smarty->assign('Hello__are_you_a_Correos_customer_', __('Hello, are you a Correos customer?', 'correosoficial'));
$this->smarty->assign('YES__CONFIGURE_MY_MODULE', __('YES, CONFIGURE MY MODULE', 'correosoficial'));
$this->smarty->assign('The_best_transport_solutions_for_your_customers_online', __('The best transport solutions for your customers online', 'correosoficial'));
$this->smarty->assign('DELIVERY_IN_CORREOS_OFFICE', __('DELIVERY IN CORREOS OFFICE', 'correosoficial'));
$this->smarty->assign('You_have_more_than_______collection_points_for_your_shipments_with_our_network_of_offices', __('You have more than 2,300 collection points for your shipments with our network of offices', 'correosoficial'));
$this->smarty->assign('SAVE_THEM_WAITING_WITH_FLEXIBLE_DELIVERY', __('SAVE THEM WAITING WITH FLEXIBLE DELIVERY', 'correosoficial'));
$this->smarty->assign('Select_the_Correos_or_Correos_Express_products_that_best_suit_you', __('Select the Correos or Correos Express products that best suit you', 'correosoficial'));
$this->smarty->assign('MINIMIZES_INCIDENTS', __('MINIMIZES INCIDENTS', 'correosoficial'));
$this->smarty->assign('Increase_your_sales_and_count_on_the_confidence_of_the_Correos_Group_for_your_shipments', __('Increase your sales and count on the confidence of the Correos Group for your shipments', 'correosoficial'));
$this->smarty->assign('ELIMINATES_UNCERTAINTY', __('ELIMINATES UNCERTAINTY', 'correosoficial'));
$this->smarty->assign('Know_the_status_of_your_shipments_at_all_times_and_offer_transparency_to_your_customer', __('Know the status of your shipments at all times and offer transparency to your customer', 'correosoficial'));
$this->smarty->assign('GIVE_THEM_PEACE_OF_MIND', __('GIVE THEM PEACE OF MIND', 'correosoficial'));
$this->smarty->assign('Your_customer_will_also_have_the_possibility_to_track_his_order_live', __('Your customer will also have the possibility to track his order live', 'correosoficial'));
$this->smarty->assign('PROMPT_DELIVERY', __('PROMPT DELIVERY', 'correosoficial'));
$this->smarty->assign('Choose_the_deadline_that_best_suits_your_type_of_shipments', __('Choose the deadline that best suits your type of shipments', 'correosoficial'));
$this->smarty->assign('I_AM_NEW__CALL_ME', __('I AM NEW, CALL ME', 'correosoficial'));
$this->smarty->assign('Leave_us_your_details__and_we_contact_you_soon', __('Leave us your details, and we contact you soon', 'correosoficial'));
$this->smarty->assign('Company_name', __('Company name', 'correosoficial'));
$this->smarty->assign('ID_number', __('ID number', 'correosoficial'));
$this->smarty->assign('Contact_name', __('Contact name', 'correosoficial'));
$this->smarty->assign('Mobile_Phone', __('Mobile Phone', 'correosoficial'));
$this->smarty->assign('Select_products_category', __('Select products category', 'correosoficial'));
$this->smarty->assign('More_than____shippings_month', __('More than 20 shippings_month', 'correosoficial'));
$this->smarty->assign('Less_than____shippings_month', __('Less than 20 shippings_month', 'correosoficial'));
$this->smarty->assign('The_fields_with___are_required_', __('The fields with * are required.', 'correosoficial'));
$this->smarty->assign('I_have_read_the_', __('I have read the ', 'correosoficial'));
$this->smarty->assign('_privacy_policy', __(' privacy policy', 'correosoficial'));
$this->smarty->assign('Send', __('Send', 'correosoficial'));
$this->smarty->assign('Please__check_errors_before_send_the_form_', __('Please, check errors before send the form.', 'correosoficial'));
$this->smarty->assign('Thank_you__We_contact_you_soon', __('Thank you. We contact you soon', 'correosoficial'));
$this->smarty->assign('Error_submitting_the_form__Please_try_again_later__If_the_error_persists__please_contact_Correos_Technical_Support_', __('Error submitting the form. Please try again later. If the error persists, please contact Correos Technical Support.', 'correosoficial'));
$this->smarty->assign('Pick_up_time_from', __('Pick up time from', 'correosoficial'));
$this->smarty->assign('Pick_up_time_to', __('Pick up time to', 'correosoficial'));
$this->smarty->assign('From_hour', __('From hour', 'correosoficial'));
$this->smarty->assign('To_hour', __('To hour', 'correosoficial'));
$this->smarty->assign('Activate_order_status_change_after_recording', __('Activate order status change after recording', 'correosoficial'));
$this->smarty->assign('Select_a_status', __('Select a status', 'correosoficial'));
$this->smarty->assign('CEX_annulled', __('CEX annulled', 'correosoficial'));
$this->smarty->assign('Cancelled', __('Cancelled', 'correosoficial'));
$this->smarty->assign('Returned_CEX', __('Returned CEX', 'correosoficial'));
$this->smarty->assign('In_progress_CEX', __('In progress CEX', 'correosoficial'));
$this->smarty->assign('Awaiting_payment_by_check', __('Awaiting payment by check', 'correosoficial'));
$this->smarty->assign('Awaiting_payment_by_bank_transfer', __('Awaiting payment by bank transfer', 'correosoficial'));
$this->smarty->assign('Pending_validation_by_cash_on_delivery', __('Pending validation by cash on delivery', 'correosoficial'));
$this->smarty->assign('Delivered', __('Delivered', 'correosoficial'));
$this->smarty->assign('Delivered_CEX', __('Delivered CEX', 'correosoficial'));
$this->smarty->assign('Sent', __('Sent', 'correosoficial'));
$this->smarty->assign('Payment_error', __('Payment error', 'correosoficial'));
$this->smarty->assign('Labelled_Correos', __('Labelled Correos', 'correosoficial'));
$this->smarty->assign('Payment_accepted', __('Payment accepted', 'correosoficial'));
$this->smarty->assign('Remote_payment_accepted', __('Remote payment accepted', 'correosoficial'));
$this->smarty->assign('Backordered_due_to_lack_of_stock__not_paid_', __('Backordered due to lack of stock (not paid)', 'correosoficial'));
$this->smarty->assign('Backordered_due_to_lack_of_stock__paid_', __('Backordered due to lack of stock (paid)', 'correosoficial'));
$this->smarty->assign('Preparation_in_progress', __('Preparation in progress', 'correosoficial'));
$this->smarty->assign('Refunded', __('Refunded', 'correosoficial'));
$this->smarty->assign('Activate_automatic_tracking', __('Activate automatic tracking', 'correosoficial'));
$this->smarty->assign('Activate_order_status_change', __('Activate order status change', 'correosoficial'));
$this->smarty->assign('Current_status', __('Current status', 'correosoficial'));
$this->smarty->assign('Annulled_status', __('Annulled status', 'correosoficial'));
$this->smarty->assign('Delivered_status', __('Delivered status', 'correosoficial'));
$this->smarty->assign('Returned_status', __('Returned status', 'correosoficial'));
$this->smarty->assign('Status_update_time', __('Status update time', 'correosoficial'));
$this->smarty->assign('hours', __('hours', 'correosoficial'));
$this->smarty->assign('The_time_selected_determines_how_often_order_statuses_are_updated_', __('The time selected determines how often order statuses are updated.', 'correosoficial'));
$this->smarty->assign('Download_log', __('Download log', 'correosoficial'));
$this->smarty->assign('Download_update_errors', __('Download update errors', 'correosoficial'));
$this->smarty->assign('Download_last_request', __('Download last request', 'correosoficial'));
$this->smarty->assign('SAVE_CRON_CONFIGURATION', __('SAVE CRON CONFIGURATION', 'correosoficial'));
$this->smarty->assign('Cron_successfully_saved', __('Cron successfully saved', 'correosoficial'));
$this->smarty->assign('Mandatory_field_for_Correos_cash_on_delivery_shipments', __('Mandatory field for Correos cash-on-delivery shipments', 'correosoficial'));
$this->smarty->assign('Show_shipment_status_progress_in_shop', __('Show shipment status progress in shop', 'correosoficial'));
$this->smarty->assign('Shipment_pre_registered', __('Shipment pre-registered', 'correosoficial'));
$this->smarty->assign('Shipment_in_progress', __('Shipment in progress', 'correosoficial'));
$this->smarty->assign('Shipment_delivered', __('Shipment delivered', 'correosoficial'));
$this->smarty->assign('Shipment_Canceled', __('Shipment Canceled', 'correosoficial'));
$this->smarty->assign('Shipment_returned', __('Shipment returned', 'correosoficial'));
$this->smarty->assign('Customs_default_description', __('Customs default description', 'correosoficial'));
$this->smarty->assign('Tariff_Code', __('Tariff Code', 'correosoficial'));
$this->smarty->assign('Required_for_COD_shipments_with_Correos__Input_IBAN_without_blank_spaces', __('Required for COD shipments with Correos. Input IBAN without blank spaces', 'correosoficial'));
$this->smarty->assign('Contract_number', __('Contract number', 'correosoficial'));
$this->smarty->assign('Customer_number', __('Customer number', 'correosoficial'));
$this->smarty->assign('Systems_Customer_Account', __('Systems Customer Account', 'correosoficial'));
$this->smarty->assign('Account_Password', __('Account Password', 'correosoficial'));
$this->smarty->assign('My_Office_User', __('My Office User', 'correosoficial'));
$this->smarty->assign('The_contract_number_must_have___numbers__for_example_________', __('The contract number must have 8 numbers, for example 12345678', 'correosoficial'));
$this->smarty->assign('The_Customer_Number_must_have___numbers__e_g__________', __('The Customer Number must have 8 numbers, e.g. 87654321', 'correosoficial'));
$this->smarty->assign('The_labelling_code_must_be___characters__letters_and_or_numbers__e_g___A_H', __('The labelling code must be 4 characters, letters and_or numbers, e.g. 1A4H', 'correosoficial'));
$this->smarty->assign('The_Client_Account_Systems_must_have_format_w_________or_W_________A_H', __('The Client Account Systems must have format w87654321 or W876543211A4H', 'correosoficial'));
$this->smarty->assign('Account_Password_must_be___alphanumeric_characters__e_g___Qs__Gn___', __('Account Password must be 8 alphanumeric characters, e.g.: Qs7(Gn8%)', 'correosoficial'));
$this->smarty->assign('The_My_Office_User_must_be_an_email_address', __('The My Office User must be an email address', 'correosoficial'));
$this->smarty->assign('Add_VAT_Number_field_at_checkout', __('Add VAT Number field at checkout', 'correosoficial'));
$this->smarty->assign('VAT_Number_Optional', __('VAT Number Optional', 'correosoficial'));
$this->smarty->assign('VAT_Number_Obligatory', __('VAT Number Obligatory', 'correosoficial'));
$this->smarty->assign('VAT_Number_Personalized', __('VAT Number Personalized', 'correosoficial'));
$this->smarty->assign('To_use_our_module_you_must_accept_our_conditions_', __('To use our module you must accept our conditions.', 'correosoficial'));
$this->smarty->assign('I_have_read_and_accept_the_', __('I have read and accept the ', 'correosoficial'));
$this->smarty->assign('terms_and_conditions', __('terms and conditions', 'correosoficial'));
$this->smarty->assign('data_protection_policy_', __('data protection policy.', 'correosoficial'));
$this->smarty->assign('I_ACCEPT', __('I ACCEPT', 'correosoficial'));
$this->smarty->assign('_Terms_and_conditions', __(' Terms and conditions', 'correosoficial'));
$this->smarty->assign('_Data_protection_policy_', __(' Data protection policy.', 'correosoficial'));
$this->smarty->assign('I_would_like_to_receive_versions_with_new_features_before_publication', __('I would like to receive versions with new features before publication', 'correosoficial'));
$this->smarty->assign('Yo_have_', __('Yo have ', 'correosoficial'));
$this->smarty->assign('_notifications_without_read_in_the_Correosoficial_module', __(' notifications without read in the Correosoficial module', 'correosoficial'));
$this->smarty->assign('Go_to_notifications', __('Go to notifications', 'correosoficial'));
$this->smarty->assign('Status', __('Status', 'correosoficial'));
$this->smarty->assign('Action_not_allowed__The_account_you_want_to_delete_has_an_associated_sender', __('Action not allowed. The account you want to delete has an associated sender', 'correosoficial'));
$this->smarty->assign('New_count', __('New count', 'correosoficial'));
$this->smarty->assign('New_contract', __('New contract', 'correosoficial'));
$this->smarty->assign('Correos_Account', __('Correos Account', 'correosoficial'));
$this->smarty->assign('CEX_Account', __('CEX Account', 'correosoficial'));
$this->smarty->assign('Default', __('Default', 'correosoficial'));
$this->smarty->assign('You_must_select_at_least_one_Correos_Account_or_Cex_Account', __('You must select at least one Correos Account or Cex Account', 'correosoficial'));
$this->smarty->assign('At_the_moment_I_am_not_going_to_use_an_Correos_account_', __('At the moment I am not going to use an Correos account.', 'correosoficial'));
$this->smarty->assign('At_the_moment_I_am_not_going_to_use_an_CEX_account_', __('At the moment I am not going to use an CEX account.', 'correosoficial'));
$this->smarty->assign('Activate_default_dimensions', __('Activate default dimensions', 'correosoficial'));
$this->smarty->assign('Default_dimensions__Kg_', __('Default dimensions (Kg)', 'correosoficial'));
$this->smarty->assign('Height__cm_', __('Height (cm)', 'correosoficial'));
$this->smarty->assign('Width__cm_', __('Width (cm)', 'correosoficial'));
$this->smarty->assign('Large__cm_', __('Large (cm)', 'correosoficial'));
$this->smarty->assign('The_minimum_dimensions_of_a_shipment_are____x____x___cm_', __('The minimum dimensions of a shipment are 15 x 10 x 1 cm.', 'correosoficial'));
$this->smarty->assign('Automatic_product_assignment___Carrier_relationship', __('Automatic product assignment - Carrier relationship', 'correosoficial'));
$this->smarty->assign('The_title_contains', __('The title contains', 'correosoficial'));
$this->smarty->assign('Search_the_carrier_name_in_the_following_text_to_capture_the_automatic_change_', __('Search the carrier name in the following text to capture the automatic change.', 'correosoficial'));
$this->smarty->assign('Product_to_assign', __('Product to assign', 'correosoficial'));
$this->smarty->assign('Select_Product', __('Select Product', 'correosoficial'));
$this->smarty->assign('Payment_method_for_COD_orders', __('Payment method for COD orders', 'correosoficial'));
$this->smarty->assign('Processing', __('Processing', 'correosoficial'));
$this->smarty->assign('ERROR________To_use_webservice_credentials__you_must_have_the_SOAP_feature_installed__Please_contact_your_hosting_for_more_information', __('ERROR 12050: To use webservice credentials, you must have the SOAP feature installed. Please contact your hosting for more information', 'correosoficial'));

$this->smarty->assign("To_use_our_module_you_must_accept_our_conditions_", __("To use our module you must accept our conditions.","correosoficial"));
$this->smarty->assign("I_have_read_and_accept_the_", __("I have read and accept the ","correosoficial"));
$this->smarty->assign("terms_and_conditions", __("terms and conditions","correosoficial"));
$this->smarty->assign("data_protection_policy_", __("data protection policy.","correosoficial"));
$this->smarty->assign("I_ACCEPT", __("I ACCEPT","correosoficial"));
$this->smarty->assign("Confirmation_", __("Confirmation?","correosoficial"));
$this->smarty->assign("Cancel", __("Cancel","correosoficial"));
$this->smarty->assign("Action", __("Action","correosoficial"));
$this->smarty->assign("Add", __("Add","correosoficial"));
$this->smarty->assign("Edit", __("Edit","correosoficial"));
$this->smarty->assign("Delete", __("Delete","correosoficial"));
$this->smarty->assign("Accept", __("Accept","correosoficial"));
$this->smarty->assign("Information", __("Information","correosoficial"));
$this->smarty->assign("An_error_has_occurred", __("An error has occurred","correosoficial"));
$this->smarty->assign("_Terms_and_conditions", __(" Terms and conditions","correosoficial"));
$this->smarty->assign("_Data_protection_policy_", __(" Data protection policy.","correosoficial"));
$this->smarty->assign("_CUSTOMER_DATA", __(" CUSTOMER DATA","correosoficial"));
$this->smarty->assign("_SENDERS", __(" SENDERS","correosoficial"));
$this->smarty->assign("_USER_CONFIGURATION", __(" USER CONFIGURATION","correosoficial"));
$this->smarty->assign("_CRON", __(" CRON","correosoficial"));
$this->smarty->assign("_PRODUCTS", __(" PRODUCTS","correosoficial"));
$this->smarty->assign("_ZONES_AND_CARRIERS", __(" ZONES AND CARRIERS","correosoficial"));
$this->smarty->assign("_CUSTOMS_PROCESSING", __(" CUSTOMS PROCESSING","correosoficial"));
$this->smarty->assign("Only_for_Correos_shippings", __("Only for Correos shippings","correosoficial"));
$this->smarty->assign("ACTIVE_CUSTOMERS", __("ACTIVE CUSTOMERS","correosoficial"));
$this->smarty->assign("id", __("id","correosoficial"));
$this->smarty->assign("Status", __("Status","correosoficial"));
$this->smarty->assign("Customer_Code", __("Customer Code","correosoficial"));
$this->smarty->assign("Company", __("Company","correosoficial"));
$this->smarty->assign("New_contract", __("New contract","correosoficial"));
$this->smarty->assign("Connected", __("Connected","correosoficial"));
$this->smarty->assign("No_connected", __("No connected","correosoficial"));
$this->smarty->assign("Contract_number", __("Contract number","correosoficial"));
$this->smarty->assign("Customer_number", __("Customer number","correosoficial"));
$this->smarty->assign("Correos_Key", __("Correos Key","correosoficial"));
$this->smarty->assign("Systems_Customer_Account", __("Systems Customer Account","correosoficial"));
$this->smarty->assign("Account_Password", __("Account Password","correosoficial"));
$this->smarty->assign("My_Office_User", __("My Office User","correosoficial"));
$this->smarty->assign("CANCEL", __("CANCEL","correosoficial"));
$this->smarty->assign("User", __("User","correosoficial"));
$this->smarty->assign("Password", __("Password","correosoficial"));
$this->smarty->assign("Do_you_want_to_delete_this_customer_", __("Do you want to delete this customer?","correosoficial"));
$this->smarty->assign("Action_not_allowed__The_account_you_want_to_delete_has_an_associated_sender", __("Action not allowed. The account you want to delete has an associated sender","correosoficial"));
$this->smarty->assign("There_is_no_customers_actives_", __("There is no customers actives.","correosoficial"));
$this->smarty->assign("Required_field", __("Required field","correosoficial"));
$this->smarty->assign("Please_enter_at_least", __("Please enter at least","correosoficial"));
$this->smarty->assign("Please_enter_no_more_than", __("Please enter no more than","correosoficial"));
$this->smarty->assign("characters", __("characters","correosoficial"));
$this->smarty->assign("The_contract_number_must_have___numbers__for_example_________", __("The contract number must have 8 numbers, for example 12345678","correosoficial"));
$this->smarty->assign("The_Customer_Number_must_have___numbers__e_g__________", __("The Customer Number must have 8 numbers, e.g. 87654321","correosoficial"));
$this->smarty->assign("The_labelling_code_must_be___characters__letters_and_or_numbers__e_g___A_H", __("The labelling code must be 4 characters, letters and_or numbers, e.g. 1A4H","correosoficial"));
$this->smarty->assign("The_Client_Account_Systems_must_have_format_w_________or_W_________A_H", __("The Client Account Systems must have format w87654321 or W876543211A4H","correosoficial"));
$this->smarty->assign("Account_Password_must_be___alphanumeric_characters__e_g___Qs__Gn___", __("Account Password must be 8 alphanumeric characters, e.g.: Qs7(Gn8%)","correosoficial"));
$this->smarty->assign("The_My_Office_User_must_be_an_email_address", __("The My Office User must be an email address","correosoficial"));
$this->smarty->assign("Your_credentials_are_correct_", __("Your credentials are correct.","correosoficial"));
$this->smarty->assign("Please__save_your_username_and_password_in_a_safe_way_", __("Please, save your username and password in a safe way.","correosoficial"));
$this->smarty->assign("Failed_to_validate_credentials_", __("Failed to validate credentials.","correosoficial"));
$this->smarty->assign("The_username_and_password_are_not_correct_", __("The username and password are not correct.","correosoficial"));
$this->smarty->assign("Service_Temporaly_unavailable__Please__try_again_later_", __("Service Temporaly unavailable. Please, try again later.","correosoficial"));
$this->smarty->assign("ERROR________To_use_webservice_credentials__you_must_have_the_SOAP_feature_installed__Please_contact_your_hosting_for_more_information", __("ERROR 12050: To use webservice credentials, you must have the SOAP feature installed. Please contact your hosting for more information","correosoficial"));
$this->smarty->assign("Sender_name", __("Sender name","correosoficial"));
$this->smarty->assign("Contact_person", __("Contact person","correosoficial"));
$this->smarty->assign("Address", __("Address","correosoficial"));
$this->smarty->assign("City", __("City","correosoficial"));
$this->smarty->assign("Zip_code", __("Zip code","correosoficial"));
$this->smarty->assign("Country", __("Country","correosoficial"));
$this->smarty->assign("Spain", __("Spain","correosoficial"));
$this->smarty->assign("Portugal", __("Portugal","correosoficial"));
$this->smarty->assign("Andorra", __("Andorra","correosoficial"));
$this->smarty->assign("Phone_number", __("Phone number","correosoficial"));
$this->smarty->assign("Email", __("Email","correosoficial"));
$this->smarty->assign("NIF_CIF", __("NIF_CIF","correosoficial"));
$this->smarty->assign("From_hour", __("From hour","correosoficial"));
$this->smarty->assign("To_hour", __("To hour","correosoficial"));
$this->smarty->assign("Correos_Account", __("Correos Account","correosoficial"));
$this->smarty->assign("At_the_moment_I_am_not_going_to_use_an_Correos_account_", __("At the moment I am not going to use an Correos account.","correosoficial"));
$this->smarty->assign("CEX_Account", __("CEX Account","correosoficial"));
$this->smarty->assign("At_the_moment_I_am_not_going_to_use_an_CEX_account_", __("At the moment I am not going to use an CEX account.","correosoficial"));
$this->smarty->assign("ADD", __("ADD","correosoficial"));
$this->smarty->assign("SAVE", __("SAVE","correosoficial"));
$this->smarty->assign("_SENDER_LIST", __(" SENDER LIST","correosoficial"));
$this->smarty->assign("Name", __("Name","correosoficial"));
$this->smarty->assign("ZP", __("ZP","correosoficial"));
$this->smarty->assign("NIF", __("NIF","correosoficial"));
$this->smarty->assign("Contact", __("Contact","correosoficial"));
$this->smarty->assign("Phone", __("Phone","correosoficial"));
$this->smarty->assign("From", __("From","correosoficial"));
$this->smarty->assign("To", __("To","correosoficial"));
$this->smarty->assign("Default_sender", __("Default sender","correosoficial"));
$this->smarty->assign("Sender_successfully_saved", __("Sender successfully saved","correosoficial"));
$this->smarty->assign("Incorrect_DNI_CIF_number__please_correct_it_before_continuing", __("Incorrect DNI_CIF number, please correct it before continuing","correosoficial"));
$this->smarty->assign("Please_enter_a_valid_email_address", __("Please enter a valid email address","correosoficial"));
$this->smarty->assign("You_must_select_at_least_one_Correos_Account_or_Cex_Account", __("You must select at least one Correos Account or Cex Account","correosoficial"));
$this->smarty->assign("Default_packages", __("Default packages","correosoficial"));
$this->smarty->assign("Default_label_type", __("Default label type","correosoficial"));
$this->smarty->assign("Payment_method_for_COD_orders", __("Payment method for COD orders","correosoficial"));
$this->smarty->assign("Bank_account_number___IBAN", __("Bank account number _ IBAN","correosoficial"));
$this->smarty->assign("Required_for_COD_shipments_with_Correos__Input_IBAN_without_blank_spaces", __("Required for COD shipments with Correos. Input IBAN without blank spaces","correosoficial"));
$this->smarty->assign("Google_Maps_API_Key", __("Google Maps API Key","correosoficial"));
$this->smarty->assign("Activate_tracking_link_in_the_customer_purchase_history", __("Activate tracking link in the customer purchase history","correosoficial"));
$this->smarty->assign("Order_remarks_to_the_label___max_____characters_", __("Order remarks to the label  (max. 80 characters)","correosoficial"));
$this->smarty->assign("Alternative_text_for_sender", __("Alternative text for sender","correosoficial"));
$this->smarty->assign("Alternative_label_text", __("Alternative label text","correosoficial"));
$this->smarty->assign("Activate_default_weight", __("Activate default weight","correosoficial"));
$this->smarty->assign("Default_weight__Kg_", __("Default weight (Kg)","correosoficial"));
$this->smarty->assign("Activate_default_dimensions", __("Activate default dimensions","correosoficial"));
$this->smarty->assign("Height__cm_", __("Height (cm)","correosoficial"));
$this->smarty->assign("Width__cm_", __("Width (cm)","correosoficial"));
$this->smarty->assign("Large__cm_", __("Large (cm)","correosoficial"));
$this->smarty->assign("Change_logo_on_labels", __("Change logo on labels","correosoficial"));
$this->smarty->assign("Only_CEX_shippings", __("Only CEX shippings","correosoficial"));
$this->smarty->assign("Activate_SSL_Certificate", __("Activate SSL Certificate","correosoficial"));
$this->smarty->assign("Activate_automatic_tracking", __("Activate automatic tracking","correosoficial"));
$this->smarty->assign("Show_shipment_status_progress_in_shop", __("Show shipment status progress in shop","correosoficial"));
$this->smarty->assign("Shipment_pre_registered", __("Shipment pre-registered","correosoficial"));
$this->smarty->assign("Shipment_Canceled", __("Shipment Canceled","correosoficial"));
$this->smarty->assign("Shipment_in_progress", __("Shipment in progress","correosoficial"));
$this->smarty->assign("Shipment_delivered", __("Shipment delivered","correosoficial"));
$this->smarty->assign("Shipment_returned", __("Shipment returned","correosoficial"));
$this->smarty->assign("Status_update_time", __("Status update time","correosoficial"));
$this->smarty->assign("hours", __("hours","correosoficial"));
$this->smarty->assign("The_time_selected_determines_how_often_order_statuses_are_updated_", __("The time selected determines how often order statuses are updated.","correosoficial"));
$this->smarty->assign("Download_log", __("Download log","correosoficial"));
$this->smarty->assign("Download_update_errors", __("Download update errors","correosoficial"));
$this->smarty->assign("Download_last_request", __("Download last request","correosoficial"));
$this->smarty->assign("Add_VAT_Number_field_at_checkout", __("Add VAT Number field at checkout","correosoficial"));
$this->smarty->assign("VAT_Number_Optional", __("VAT Number Optional","correosoficial"));
$this->smarty->assign("VAT_Number_Obligatory", __("VAT Number Obligatory","correosoficial"));
$this->smarty->assign("VAT_Number_Personalized", __("VAT Number Personalized","correosoficial"));
$this->smarty->assign("I_would_like_to_receive_versions_with_new_features_before_publication", __("I would like to receive versions with new features before publication","correosoficial"));
$this->smarty->assign("Processing", __("Processing","correosoficial"));
$this->smarty->assign("SAVE_USER_DATA", __("SAVE USER DATA","correosoficial"));
$this->smarty->assign("User_data_successfully_saved", __("User data successfully saved","correosoficial"));
$this->smarty->assign("Please_enter_a_value_greater_than_or_equal_to__", __("Please enter a value greater than or equal to 1","correosoficial"));
$this->smarty->assign("Please_enter_a_value_less_than_or_equal_to___", __("Please enter a value less than or equal to 10","correosoficial"));
$this->smarty->assign("Allowable_value_between___and____kg", __("Allowable value between 1 and 30 kg","correosoficial"));
$this->smarty->assign("The_minimum_dimensions_of_a_shipment_are____x____x___cm_", __("The minimum dimensions of a shipment are 15 x 10 x 1 cm.","correosoficial"));
$this->smarty->assign("Please_specify_a_valid_Bank_Account_number_IBAN", __("Please specify a valid Bank Account number_IBAN","correosoficial"));
$this->smarty->assign("Select_the_products_to_be_displayed_in_the_checkout", __("Select the products to be displayed in the checkout","correosoficial"));
$this->smarty->assign("Correos", __("Correos","correosoficial"));
$this->smarty->assign("Correos_Express", __("Correos Express","correosoficial"));
$this->smarty->assign("SAVE_PRODUCTS", __("SAVE PRODUCTS","correosoficial"));
$this->smarty->assign("No_Customers_Active", __("No Customers Active","correosoficial"));
$this->smarty->assign("If_you_already_has_a_Customer_Code__please_go_to_CUSTOMER_DATA", __("If you already has a Customer Code, please go to CUSTOMER DATA","correosoficial"));
$this->smarty->assign("Products_successfully_saved", __("Products successfully saved","correosoficial"));
$this->smarty->assign("Carriers_with____are_carriers_that_are_not_active", __("Carriers with ** are carriers that are not active","correosoficial"));
$this->smarty->assign("It_is_recommended_to_configure_them_for_backward_compatibility", __("It is recommended to configure them for backward compatibility","correosoficial"));
$this->smarty->assign("Activate_all_carriers", __("Activate all carriers","correosoficial"));
$this->smarty->assign("Automatic_product_assignment___Carrier_relationship", __("Automatic product assignment - Carrier relationship","correosoficial"));
$this->smarty->assign("The_title_contains", __("The title contains","correosoficial"));
$this->smarty->assign("Search_the_carrier_name_in_the_following_text_to_capture_the_automatic_change_", __("Search the carrier name in the following text to capture the automatic change.","correosoficial"));
$this->smarty->assign("Product_to_assign", __("Product to assign","correosoficial"));
$this->smarty->assign("Select_Product", __("Select Product","correosoficial"));
$this->smarty->assign("SAVE_ZONES_AND_CARRIERS", __("SAVE ZONES AND CARRIERS","correosoficial"));
$this->smarty->assign("Zones_and_carriers_successfully_saved", __("Zones and carriers successfully saved","correosoficial"));
$this->smarty->assign("Reference_of_customs_consignor", __("Reference of customs consignor","correosoficial"));
$this->smarty->assign("Message_to_warn_the_buyer_about_customs_formalities__max______characters_", __("Message to warn the buyer about customs formalities (max. 100 characters)","correosoficial"));
$this->smarty->assign("Message_to_warn_the_buyer", __("Message to warn the buyer","correosoficial"));
$this->smarty->assign("This_shipment_is_subject_to_customs_clearance__The_price_of_the_shipment_may_be_increased", __("This shipment is subject to customs clearance. The price of the shipment may be increased","correosoficial"));
$this->smarty->assign("Select_Customs_Description_or_Default_Tariff_Number", __("Select Customs Description or Default Tariff Number","correosoficial"));
$this->smarty->assign("Customs_default_description", __("Customs default description","correosoficial"));
$this->smarty->assign("Tariff_Code", __("Tariff Code","correosoficial"));
$this->smarty->assign("Default_customs_description", __("Default customs description","correosoficial"));
$this->smarty->assign("Tariff_code", __("Tariff code","correosoficial"));
$this->smarty->assign("Description", __("Description","correosoficial"));
$this->smarty->assign("SAVE_CUSTOMS_PROCESSING", __("SAVE CUSTOMS PROCESSING","correosoficial"));
$this->smarty->assign("Customs_Processing_successfully_saved", __("Customs Processing successfully saved","correosoficial"));
$this->smarty->assign("Input_data_must_be______or____characters_long", __("Input data must be 6, 8 or 10 characters long","correosoficial"));
