<?php
/**
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see https://www.gnu.org/licenses/.
 */

$this->smarty->assign('Mass_Product_Management', __('Mass Product Management', 'correosoficial'));
$this->smarty->assign('Label_Reprint', __('Label Reprint', 'correosoficial'));
$this->smarty->assign('Order_Summary', __('Order Summary', 'correosoficial'));
$this->smarty->assign('Pickups', __('Pickups', 'correosoficial'));
$this->smarty->assign('Generation_of_Customs_Documentation', __('Generation of Customs Documentation', 'correosoficial'));
$this->smarty->assign('Customs_Processing_successfully_saved', __('Customs Processing successfully saved', 'correosoficial'));
$this->smarty->assign('The_selected_carrier_does_not_allow_shipments_of_multiple_packages', __('The selected carrier does not allow shipments of multiple packages', 'correosoficial'));
$this->smarty->assign('The_maximum_number_of_packages_for_this_product_is', __('The maximum number of packages for this product is', 'correosoficial'));
$this->smarty->assign('Shipping_number_', __('Shipping number:', 'correosoficial'));
$this->smarty->assign('You_cannot_change_from_a_Home_delivery_method_to_CityPaq_or_Office', __('You cannot change from a Home delivery method to CityPaq or Office', 'correosoficial'));
$this->smarty->assign('You_cannot_change_from_a_CityPaq_delivery_method_to_Office', __('You cannot change from a CityPaq delivery method to Office', 'correosoficial'));
$this->smarty->assign('You_cannot_change_from_a_Office_delivery_method_to_CityPaq', __('You cannot change from a Office delivery method to CityPaq', 'correosoficial'));
$this->smarty->assign('Must_select_at_least_one_record_of_the_table', __('Must select at least one record of the table', 'correosoficial'));
$this->smarty->assign('Date___to___is_minor_than_date___from__', __('Date «to» is minor than date «from»', 'correosoficial'));
$this->smarty->assign('Must_select_a_package_size', __('Must select a package size', 'correosoficial'));
$this->smarty->assign('It_is_not_possible_to_request_collection_for_the_same_day_in_Correos_shipments', __('It is not possible to request collection for the same day in Correos shipments', 'correosoficial'));
$this->smarty->assign('It_is_not_possible_to_request_collection_for_dates_after____days', __('It is not possible to request collection for dates after 30 days', 'correosoficial'));
$this->smarty->assign('It_is_not_possible_to_request_collection_for_past_dates', __('It is not possible to request collection for past dates', 'correosoficial'));
$this->smarty->assign('Please__cancel_first_the_preregister_in_orders_managment_to_do_a_new_preregistration_request', __('Please, cancel first the preregister in orders managment to do a new preregistration request', 'correosoficial'));
$this->smarty->assign('Please__cancel_first_the_preregister_in_orders_managment_to_do_a_new_collection_request', __('Please, cancel first the preregister in orders managment to do a new collection request', 'correosoficial'));
$this->smarty->assign('Only_apply_to_CEX_products_and_Portugal_Shippings', __('Only apply to CEX products and Portugal Shippings', 'correosoficial'));
$this->smarty->assign('AT_Code_required__Please__enter_no_more_than____characters', __('AT Code required. Please, enter no more than 30 characters', 'correosoficial'));
$this->smarty->assign('Portugal_Shippings_require_the_AT_Code', __('Portugal Shippings require the AT Code', 'correosoficial'));
$this->smarty->assign('From', __('From', 'correosoficial'));
$this->smarty->assign('Untill', __('Untill', 'correosoficial'));
$this->smarty->assign('Search_orders', __('Search orders', 'correosoficial'));
$this->smarty->assign('MASS_PRODUCT_MANAGMENT', __('MASS PRODUCT MANAGMENT', 'correosoficial'));
$this->smarty->assign('Reference', __('Reference', 'correosoficial'));
$this->smarty->assign('Shipping_Number_', __('Shipping Number ', 'correosoficial'));
$this->smarty->assign('Carrier', __('Carrier', 'correosoficial'));
$this->smarty->assign('Status_', __('Status ', 'correosoficial'));
$this->smarty->assign('Customer', __('Customer', 'correosoficial'));
$this->smarty->assign('Date_Hour', __('Date/Hour', 'correosoficial'));
$this->smarty->assign('Office', __('Office', 'correosoficial'));
$this->smarty->assign('Selected_Product', __('Selected Product', 'correosoficial'));
$this->smarty->assign('Change_product', __('Change product', 'correosoficial'));
$this->smarty->assign('Packages', __('Packages', 'correosoficial'));
$this->smarty->assign('Shipping_Number', __('Shipping Number', 'correosoficial'));
$this->smarty->assign('AT_Code', __('AT Code', 'correosoficial'));
$this->smarty->assign('ERRORS_IN_ORDERS_GENERATION', __('ERRORS IN ORDERS GENERATION', 'correosoficial'));
$this->smarty->assign('Print_label_at_pickup', __('Print label at pickup', 'correosoficial'));
$this->smarty->assign('Postage_only__Click_if_Correos_must_carry_the_printed_labels_in_the_collection', __('Postage only. Click if Correos must carry the printed labels in the collection', 'correosoficial'));
$this->smarty->assign('Package_Size', __('Package Size', 'correosoficial'));
$this->smarty->assign('Medium', __('Medium', 'correosoficial'));
$this->smarty->assign('Small__Shoes_Box_', __('Small (Shoes Box)', 'correosoficial'));
$this->smarty->assign('Medium__Sheet_Box_', __('Medium (Sheet Box)', 'correosoficial'));
$this->smarty->assign('Big__box___x__x__cm_', __('Big (box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Very_Big__greather_than_box___x__x__cm_', __('Very Big (greather than box 80x80x80cm)', 'correosoficial'));
$this->smarty->assign('Pallete', __('Pallete', 'correosoficial'));
$this->smarty->assign('Only_send_Correos', __('Only send Correos', 'correosoficial'));
$this->smarty->assign('LABEL_REPRINT', __('LABEL REPRINT', 'correosoficial'));
$this->smarty->assign('Receiver_name', __('Receiver name', 'correosoficial'));
$this->smarty->assign('Receiver_address', __('Receiver address', 'correosoficial'));
$this->smarty->assign('Date_Hour_recording_', __('Date/Hour recording ', 'correosoficial'));
$this->smarty->assign('ORDER_SUMMARY', __('ORDER SUMMARY', 'correosoficial'));
$this->smarty->assign('PICKUPS', __('PICKUPS', 'correosoficial'));
$this->smarty->assign('Receiver_', __('Receiver ', 'correosoficial'));
$this->smarty->assign('Sender_Address_', __('Sender Address ', 'correosoficial'));
$this->smarty->assign('Pickup_recorded_', __('Pickup recorded ', 'correosoficial'));
$this->smarty->assign('Size', __('Size', 'correosoficial'));
$this->smarty->assign('Pickup_label', __('Pickup label', 'correosoficial'));
$this->smarty->assign('Pickup_recorded', __('Pickup recorded', 'correosoficial'));
$this->smarty->assign('ERRORS_IN_PICKUP_ORDERS', __('ERRORS IN PICKUP ORDERS', 'correosoficial'));
$this->smarty->assign('Collections_of_shipments_already_admitted_will_not_be_recorded', __('Collections of shipments already admitted will not be recorded', 'correosoficial'));
$this->smarty->assign('Customs_Documentation', __('Customs Documentation', 'correosoficial'));
$this->smarty->assign('Search_shipments', __('Search shipments', 'correosoficial'));
$this->smarty->assign('GENERATION_OF_CUSTOMS_DOCUMENTATION', __('GENERATION OF CUSTOMS DOCUMENTATION', 'correosoficial'));
$this->smarty->assign('Shipping_Ref_', __('Shipping Ref.', 'correosoficial'));
$this->smarty->assign('Shipping_Code', __('Shipping Code', 'correosoficial'));
$this->smarty->assign('Name_of_addressee', __('Name of addressee', 'correosoficial'));
$this->smarty->assign('Address_of_addressee', __('Address of addressee', 'correosoficial'));
$this->smarty->assign('Country_of_addressee', __('Country of addressee', 'correosoficial'));
$this->smarty->assign('Date_of_creation', __('Date of creation', 'correosoficial'));
$this->smarty->assign('Shipping_Ref', __('Shipping Ref', 'correosoficial'));
$this->smarty->assign('ERRORS_IN_GENERATION_OF_CUSTOMS_DOCUMENTATION', __('ERRORS IN GENERATION OF CUSTOMS DOCUMENTATION', 'correosoficial'));
$this->smarty->assign('Print_CN__', __('Print CN23', 'correosoficial'));
$this->smarty->assign('Print_DCAF', __('Print DCAF', 'correosoficial'));
$this->smarty->assign('Print_DDP', __('Print DDP', 'correosoficial'));
$this->smarty->assign('Confirmation_', __('Confirmation?', 'correosoficial'));
$this->smarty->assign('Cancel', __('Cancel', 'correosoficial'));
$this->smarty->assign('Action', __('Action', 'correosoficial'));
$this->smarty->assign('Add', __('Add', 'correosoficial'));
$this->smarty->assign('Edit', __('Edit', 'correosoficial'));
$this->smarty->assign('Delete', __('Delete', 'correosoficial'));
$this->smarty->assign('Accept', __('Accept', 'correosoficial'));
$this->smarty->assign('Information', __('Information', 'correosoficial'));
$this->smarty->assign('An_error_has_occurred', __('An error has occurred', 'correosoficial'));
$this->smarty->assign('Mass_Orders_Management', __('Mass Orders Management', 'correosoficial'));
$this->smarty->assign('MASS_ORDERS_MANAGMENT', __('MASS ORDERS MANAGMENT', 'correosoficial'));
$this->smarty->assign('Only_Correos_shipments__Click_if_Correos_must_have_the_labels_printed_on_the_collection', __('Only Correos shipments. Click if Correos must have the labels printed on the collection', 'correosoficial'));
$this->smarty->assign('Only_Correos_shipments__Select_package_size_for_pickup_', __('Only Correos shipments. Select package size for pickup.', 'correosoficial'));
$this->smarty->assign('Please__go_to_order_and_specify_packages_measurements_and_weight', __('Please, go to order and specify packages measurements and weight', 'correosoficial'));
$this->smarty->assign('Status', __('Status', 'correosoficial'));
$this->smarty->assign('Only_Correos_shipments__Click_if_Correos_must_have_the_labels_printed_on_pickup', __('Only Correos shipments. Click if Correos must have the labels printed on pickup', 'correosoficial'));
$this->smarty->assign('Default_sender', __('Default sender', 'correosoficial'));
$this->smarty->assign('You_have_not_configured_any_default_sender', __('You have not configured any default sender', 'correosoficial'));
$this->smarty->assign('Date_Hour_recording', __('Date/Hour recording', 'correosoficial'));
$this->smarty->assign('Receiver', __('Receiver', 'correosoficial'));
$this->smarty->assign('Sender_Address', __('Sender Address', 'correosoficial'));
$this->smarty->assign('ORDER', __('ORDER', 'correosoficial'));
$this->smarty->assign('Choose_a_package_size_for_pickup', __('Choose a package size for pickup', 'correosoficial'));
$this->smarty->assign('Envelopes', __('Envelopes', 'correosoficial'));
$this->smarty->assign('Click_on_each_item_in_the_list_to_show_hide_columns_of_the_table', __('Click on each item in the list to show_hide columns of the table', 'correosoficial'));
$this->smarty->assign('Show_Hide_columns', __('Show/Hide columns', 'correosoficial'));
$this->smarty->assign('Error', __('Error', 'correosoficial'));
$this->smarty->assign('Save_pickup', __('Save pickup', 'correosoficial'));
$this->smarty->assign('Pickup_date', __('Pickup date', 'correosoficial'));
$this->smarty->assign('From_hour', __('From hour', 'correosoficial'));
$this->smarty->assign('To_hour', __('To hour', 'correosoficial'));
$this->smarty->assign('Label_type', __('Label type', 'correosoficial'));
$this->smarty->assign('Processing', __('Processing', 'correosoficial'));
$this->smarty->assign('Generate_shippings', __('Generate shippings', 'correosoficial'));
$this->smarty->assign('Generate_pickups', __('Generate pickups', 'correosoficial'));
$this->smarty->assign('Label_Format', __('Label Format', 'correosoficial'));
$this->smarty->assign('Products', __('Products', 'correosoficial'));
$this->smarty->assign('In_this_tab_only_show_the_Correos_orders__anywhere_show_CEX_orders', __('In this tab only show the Correos orders, anywhere show CEX orders', 'correosoficial'));
$this->smarty->assign('Paq Light Internacional is not available in your ubication', __('Paq Light Internacional is not available in your ubication'));
$this->smarty->assign('There are no transports for your location in Paq Light Internacional', __('There are no transports for your location in Paq Light Internacional'));
$this->smarty->assign('Messages_center', __('Messages center', 'correosoficial'));
$this->smarty->assign('Click_on_any_notification_to_see_it_in_this_space_in_more_detail', __('Click on any notification to see it in this space in more detail', 'correosoficial'));
$this->smarty->assign('You_don_t_have_any_notification', __("You don\t have any notification", 'correosoficial'));
$this->smarty->assign('To_use_our_module_you_must_accept_our_conditions_', __('To use our module you must accept our conditions.', 'correosoficial'));
$this->smarty->assign('I_have_read_and_accept_the_', __('I have read and accept the ', 'correosoficial'));
$this->smarty->assign('terms_and_conditions', __('terms and conditions', 'correosoficial'));
$this->smarty->assign('data_protection_policy_', __('data protection policy.', 'correosoficial'));
$this->smarty->assign('I_ACCEPT', __('I ACCEPT', 'correosoficial'));
$this->smarty->assign('Show_Hide_columns', __('Show_Hide columns', 'correosoficial'));
$this->smarty->assign('Selected_Sender', __('Selected Sender', 'correosoficial'));
$this->smarty->assign('Date_Hour_recording', __('Date_Hour recording', 'correosoficial'));
$this->smarty->assign('Date_Hour_recording_', __('Date_Hour recording ', 'correosoficial'));
$this->smarty->assign('Date_Hour', __('Date_Hour', 'correosoficial'));
$this->smarty->assign('Search_by_labeling_date', __('Search by labeling date', 'correosoficial'));
$this->smarty->assign('Senders', __('Senders', 'correosoficial'));
$this->smarty->assign('Todos', __('Todos', 'correosoficial'));
$this->smarty->assign('Recipient_name', __('Recipient name', 'correosoficial'));
$this->smarty->assign('Shipping_address', __('Shipping address', 'correosoficial'));
$this->smarty->assign('Sender', __('Sender', 'correosoficial'));
$this->smarty->assign('Labeling_date', __('Labeling date', 'correosoficial'));
$this->smarty->assign('Package_code', __('Package code', 'correosoficial'));
$this->smarty->assign('Customer_code', __('Customer code', 'correosoficial'));
$this->smarty->assign('Manifested', __('Manifested', 'correosoficial'));
$this->smarty->assign('Manifest_date', __('Manifest_date', 'correosoficial'));
$this->smarty->assign('Manifest_date', __('Manifest date', 'correosoficial'));
$this->smarty->assign('CP', __('CP', 'correosoficial'));
$this->smarty->assign('ERRORS_IN_PRINT_LABEL_GENERATION', __('ERRORS IN PRINT LABEL GENERATION', 'correosoficial'));
$this->smarty->assign('Order_Summary', __('Order Summary', 'correosoficial'));
$this->smarty->assign('From', __('From', 'correosoficial'));
$this->smarty->assign('Untill', __('Untill', 'correosoficial'));
$this->smarty->assign('Search_by_labeling_date', __('Search by labeling date', 'correosoficial'));
$this->smarty->assign('Senders', __('Senders', 'correosoficial'));
$this->smarty->assign('All', __('All', 'correosoficial'));
$this->smarty->assign('Search_orders', __('Search orders', 'correosoficial'));
$this->smarty->assign('ORDER_SUMMARY', __('ORDER SUMMARY', 'correosoficial'));
$this->smarty->assign('Show_Hide_columns', __('Show_Hide columns', 'correosoficial'));
$this->smarty->assign('Reference', __('Reference', 'correosoficial'));
$this->smarty->assign('Shipping_Code', __('Shipping Code', 'correosoficial'));
$this->smarty->assign('Package_code', __('Package code', 'correosoficial'));
$this->smarty->assign('Carrier', __('Carrier', 'correosoficial'));
$this->smarty->assign('Recipient_name', __('Recipient name', 'correosoficial'));
$this->smarty->assign('Shipping_address', __('Shipping address', 'correosoficial'));
$this->smarty->assign('CP', __('CP', 'correosoficial'));
$this->smarty->assign('Date_Hour_recording', __('Date_Hour recording', 'correosoficial'));
$this->smarty->assign('Labeling_date', __('Labeling date', 'correosoficial'));
$this->smarty->assign('Manifested', __('Manifested', 'correosoficial'));
$this->smarty->assign('Manifest_date', __('Manifest_date', 'correosoficial'));
$this->smarty->assign('Customer_code', __('Customer code', 'correosoficial'));
