let $ = jQuery;
const msgsp = function(text, ico = false){if(!ico){var img = '<i class="spuser_alert_img material-symbols-outlined">warning</i>';}else{var img = '<i class="spuser_alert_img material-symbols-outlined">check_circle</i>';}var el = $("<div />",{class: 'spuser_alert'});el.append($("<div />",{ class: 'spuser_alert_cont' }).append( $("<a />",{href:"#", class: 'spuser_alert_close', text: "x"}).on("click", function(e) { e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); }) ).append( img  ).append( $("<p />",{class: 'spuser_alert_text', html: text}) ));$("body").append(el);setTimeout(function(){ el.addClass("show"); }, 100);return;}
const msgsp_confirm = function(text, fun){var img = '<i class="spuser_alert_img material-symbols-outlined">warning</i>';var el = $("<div />",{class: 'spuser_alert'});el.append($("<div />",{ class: 'spuser_alert_cont' }).append($("<a />",{href:"#", class: 'spuser_alert_close', text: "x"}).on("click", function(e) { e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); })).append( img ).append( $("<p />",{class: 'spuser_alert_text', html: text}) ).append( $("<div />",{class: 'spuser_alert_btns'}).append($("<a />",{href:"#", class: 'spuser_alert_btn spuser_alert_accept', text: "Si"}).on("click", function(e) { fun(); e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); })).append($("<a />",{href:"#", class: 'spuser_alert_btn spuser_alert_cancel', text: "No"}).on("click", function(e) { fun; e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); })) ));$("body").append(el);setTimeout(function(){ el.addClass("show"); }, 100);return;}
const msgsp_options = function(text, funs){let el = $("<div />",{class: 'spuser_alert'}).append($("<div />",{ class: 'spuser_alert_cont' }).append($("<a />",{href:"#", class: 'spuser_alert_close', text: "x"}).on("click", function(e) { e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); })).append( $("<p />",{class: 'spuser_alert_text p-0', html: text}) ).append( $("<div />",{class: 'spuser_alert_btns ml-0'}) ));let bts = el.find('.spuser_alert_btns');$.each(funs, (nam, fun) => {bts.append($("<a />",{href:"#", class: 'spuser_alert_btn spuser_alert_multiple', text: nam}).on("click", function(e) { fun(); e.preventDefault(); el.removeClass("show"); setTimeout(function(){ el.remove() }, 600); }))});$("body").append(el);setTimeout(function(){ el.addClass("show"); }, 100);return;}
const loading = function(text){var el = $("#spuser_loading");if(!el.length){el = $('<div class="spuser_modal" id="spuser_loading"><div class="spuser_modal_load"><p class="spuser_modal_load_title"><span id="load-msg">Cargando</span><span>.</span><span>.</span><span>.</span></p></div></div>')};el.find("#load-msg").text(text);$("body").append(el);el.fadeIn();}
const loading_end = function(time = 0){var el = $("#spuser_loading");if(el.length > 0){setTimeout(function(){el.fadeOut();setTimeout(function() { el.remove();}, 500);}, time);}}
const isEmail = (email) => { var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/; return regex.test(email); };
const isObject = (obj) => (typeof obj === 'object' && obj !== null);


